theme: jekyll-theme-slate
title: GEARS
show_downloads: true
github:
  zip_url: https://github.com/jintonic/gears/zipball/master
  tar_url: https://github.com/jintonic/gears/tarball/master
  
plugins:
  - jekyll-mentions

g4doc: http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/html
g4git: https://gitlab.cern.ch/geant4/geant4/tree/master/source
xyz: http://physino.xyz/gears
file: https://github.com/jintonic/gears/blob/master
